plugin:
    name: 'mainpixel.ocreviewsplugin::lang.plugin.name'
    description: 'mainpixel.ocreviewsplugin::lang.plugin.description'
    author: 'Job Verplanke'
    icon: oc-icon-adn
    homepage: 'https://www.mainpixel.io/en/contact-mainpixel/sales'
navigation:
    main-menu-item:
        label: Test
        url: mainpixel/ocreviewsplugin/reviews
        icon: icon-apple
        sideMenu:
            side-menu-item:
                label: Reviews
                url:
                icon: icon-bed
