list: $/mainpixel/ocreviewsplugin/models/review/columns.yaml
modelClass: Mainpixel\OcReviewsPlugin\Models\Review
title: Reviews
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mainpixel/ocreviewsplugin/reviews/update/:id'
